GET http://localhost:3000/api
Authorization: Bearer 
###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjIiLCJpYXQiOjE3ODI0MjU0NTl9.jas0dENfXghXUTLWSWLLly1eYiv65XX5AaVyYsD4RYo"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "user2"
}